{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "hello.serviceAccountName" . }}
  labels:
{{ include "hello.labels" . | indent 4 }}
{{- end -}}
